### ISSUE TITLE
CT: Cannot add a listener to a disposed TinyEmitter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#174]
```
rutherford-scattering : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/rutherford-scattering/rutherford-scattering_en.html?continuousTest=%7B%22test%22%3A%5B%22rutherford-scattering%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1667521640987%22%2C%22timestamp%22%3A1667525150351%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Cannot add a listener to a disposed TinyEmitter
Error: Assertion failed: Cannot add a listener to a disposed TinyEmitter
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/assert/js/assert.js:28:13)
at assert (TinyEmitter.ts:120:14)
at addListener (TinyProperty.ts:147:9)
at lazyLink (LayoutConstraint.ts:74:25)
at addNode (ButtonNode.ts:435:9)
at (ButtonNode.ts:218:34)
at (RectangularButton.ts:177:4)
at (RectangularRadioButton.ts:111:4)
at (RectangularRadioButtonGroup.ts:223:26)
at (RutherfordAtomScreenView.js:155:48)
id: Bayes Puppeteer
Snapshot from 11/3/2022, 6:27:20 PM
```

**Comment by jessegreenberg** [comment]
This was related to https://github.com/phetsims/sun/issues/746, since RectangularRadioButtonGroup disposes the nodes it creates from `createNode`, a single instance of a Node cannot be reused for the `createNode` function when disposing/re-instantiating a RectangularRadioButtonGroup.
