### ISSUE TITLE
rutherford-scattering has invalid aspect ratio for screen icons

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rutherford-scattering#9]
```
Uncaught Error: Assertion failed: NavigationBar icons for screen 0 did not have a valid aspect ratio.
Error: Assertion failed: NavigationBar icons for screen 0 did not have a valid aspect ratio.
    at window.assertions.assertFunction (http://localhost/~cmalley/Github/assert/js/assert.js:22:13)
    at new NavigationBar (http://localhost/~cmalley/Github/joist/js/NavigationBar.js?bust=1440520055197:73:93)
    at new Sim (http://localhost/~cmalley/Github/joist/js/Sim.js?bust=1440520055197:369:25)
    at http://localhost/~cmalley/Github/rutherford-scattering/js/rutherford-scattering-main.js?bust=1440520055197:29:15
    at doneLoadingImages (http://localhost/~cmalley/Github/joist/js/SimLauncher.js?bust=1440520055197:31:9)
    at Object.launch (http://localhost/~cmalley/Github/joist/js/SimLauncher.js?bust=1440520055197:51:9)
    at http://localhost/~cmalley/Github/rutherford-scattering/js/rutherford-scattering-main.js?bust=1440520055197:28:15
    at Object.context.execCb (http://localhost/~cmalley/Github/sherpa/lib/require-2.1.11.js:1650:25)
    at Object.Module.check (http://localhost/~cmalley/Github/sherpa/lib/require-2.1.11.js:866:35)
    at Object. (http://localhost/~cmalley/Github/sherpa/lib/require-2.1.11.js:1113:20)
```

**Comment by pixelzoom** [comment]
I'll take care of this so I don't have to see it in test-server output.

**Comment by pixelzoom** [comment]
Fixed. Closing.
